name: Nighty Plugins

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: JX3BOT Nighty（WeChat）
        path: ./target/JX3BOT-WXSocket-1.0-SNAPSHOT.jar
